stages:
  preprocess_dataset:
    foreach:
      - WikiCS
      - Amazon-CS
      - Amazon-Photo
      - Coauthor-CS
      - Coauthor-Physics
      - ogbn-arxiv
      - PPI
      - ogbn-products
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/preprocess_dataset.py ${item}
      deps:
        - experiments/scripts/preprocess_dataset.py
      outs:
        - data/datasets/${item}/

  ### Full batch scenario
  full_batch_hps:
    foreach:
      - WikiCS
      - Amazon-CS
      - Amazon-Photo
      - Coauthor-CS
      - Coauthor-Physics
      - ogbn-arxiv
      - PPI
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/full_batch/hps.py ${item}
      params:
        - experiments/configs/full_batch/hps.yaml:
            - ${item}
      deps:
        - experiments/scripts/full_batch/hps.py
        - data/datasets/${item}/
      outs:
        - data/full_batch/hps/${item}/log.csv
        - data/full_batch/hps/${item}/best.json

  full_batch_train:
    foreach:
      - WikiCS
      - Amazon-CS
      - Amazon-Photo
      - Coauthor-CS
      - Coauthor-Physics
      - ogbn-arxiv
      - PPI
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/full_batch/train.py ${item}
      params:
        - experiments/configs/full_batch/train.yaml:
            - ${item}
        - data/full_batch/hps/${item}/best.json:
            - SAME
      deps:
        - experiments/scripts/full_batch/train.py
        - gssl/full_batch/model.py
        - data/datasets/${item}/
      outs:
        - data/full_batch/train/${item}/

  ### Batched scenario
  batched_train:
    foreach:
      - WikiCS
      - Amazon-CS
      - Amazon-Photo
      - Coauthor-CS
      - Coauthor-Physics
      - ogbn-arxiv
      - PPI
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/batched/train.py ${item}
      params:
        - experiments/configs/batched/train.yaml:
            - ${item}
        - data/full_batch/hps/${item}/best.json:
            - SAME
      deps:
        - experiments/scripts/batched/train.py
        - data/datasets/${item}/
      outs:
        - data/batched/train/${item}/

  ### OGBn-Products
  batched_hps_ogbn_products:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/batched/hps.py ogbn-products
    params:
      - experiments/configs/batched/hps.yaml:
          - ogbn-products
    deps:
      - experiments/scripts/batched/hps.py
      - data/datasets/ogbn-products/
    outs:
      - data/batched/hps/ogbn-products/log.csv
      - data/batched/hps/ogbn-products/best.json

  batched_train_ogbn_products:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/batched/train.py ogbn-products
    params:
      - experiments/configs/batched/train.yaml:
          - ogbn-products
      - data/batched/hps/ogbn-products/best.json:
          - SAME
    deps:
      - experiments/scripts/batched/train.py
      - data/datasets/ogbn-products/
    outs:
      - data/batched/train/ogbn-products/

  ### Additional experiments
  compare_augmentation_hyperparameter_sets:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/compare_augmentation_hyperparameter_sets.py
    deps:
      - experiments/scripts/compare_augmentation_hyperparameter_sets.py
      - data/full_batch/hps/
    outs:
      - data/augmentation_hyperparameter_plot.png

  compare_running_times:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/time/compare_running_times.py
    deps:
      - experiments/scripts/time/compare_running_times.py
    outs:
      - data/time/log.csv
      - data/time/summary_table.txt

  train_bgrl_full_batch:
    foreach:
      - WikiCS
      - Amazon-CS
      - Amazon-Photo
      - Coauthor-CS
      # - Coauthor-Physics  # OOM
      # - ogbn-arxiv
      # - PPI
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/full_batch/train_bgrl.py ${item}
      params:
        - experiments/configs/full_batch/train_bgrl.yaml:
            - ${item}
      deps:
        - experiments/scripts/full_batch/train_bgrl.py
        - data/datasets/${item}/
      outs:
        - data/full_batch/train_bgrl/${item}/

  bgrl_hps_batched:
    foreach:
      - ogbn-products
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/batched/hps_bgrl.py ${item}
      params:
        - experiments/configs/batched/hps_bgrl.yaml:
            - ${item}
      deps:
        - experiments/scripts/batched/hps_bgrl.py
        - data/datasets/${item}/
      outs:
        - data/batched/hps_bgrl/${item}/log.csv
        - data/batched/hps_bgrl/${item}/best.json

  bgrl_batched_train:
    foreach:
      - ogbn-products
    do:
      wdir: .
      cmd: PYTHONPATH=. python3 experiments/scripts/batched/train_bgrl.py ${item}
      params:
        - experiments/configs/batched/train_bgrl.yaml:
            - ${item}
        - data/batched/hps_bgrl/${item}/best.json:
            - SAME
      deps:
        - experiments/scripts/batched/train_bgrl.py
        - data/datasets/${item}/
      outs:
        - data/batched/train_bgrl/${item}/

  evaluate_features_products:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/products/features.py
    deps:
      - experiments/scripts/products/features.py
      - data/datasets/ogbn-products/
    outs:
      - data/products/features.json

  evaluate_deepwalk_products:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/products/deepwalk.py
    deps:
      - experiments/scripts/products/deepwalk.py
      - data/datasets/ogbn-products/
    outs:
      - data/products/deepwalk.json
      - data/products/deepwalk_features.json

  run_lambda_ablation:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/run_lambda_ablation.py
    deps:
    - experiments/scripts/run_lambda_ablation.py
    outs:
    - data/lambda_ablation_results.csv

  make_lambda_ablation_plot:
    wdir: .
    cmd: PYTHONPATH=. python3 experiments/scripts/make_lambda_ablation_plot.py
    deps:
    - experiments/scripts/make_lambda_ablation_plot.py
    - data/lambda_ablation_results.csv
    outs:
    - data/lambda_ablation_plot.png
